In [5]:
import numpy as np

In [8]:
#1  Create a 3×3 numpy array of all True’s 
x=np.ones((3,3),dtype=bool)
x

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
#2 Extract all odd numbers from arrays 
n=np.arange(10)
n


array([2])

In [15]:
n[n%2==1]

array([1, 3, 5, 7, 9])

In [17]:
#3 Replace all even numbers in above array with -5 
n[n%2==0]

array([0, 2, 4, 6, 8])

In [20]:
#4 Reshape an array 
print(n)
n.reshape(2,5)

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
#5 How to get the positions where elements of two arrays match 

a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8]) 

(a==b).all()

False

In [25]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [27]:
np.sum(a==b)

4

In [39]:
#6 Swap columns 1 and 2 in the array 
s=np.array([[1,2,3],[4,5,6],[7,8,9]])
s


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
s[:, [1, 0]] = s[:, [0, 1]]
print("after swaping the array :", "\n",s)

after swaping the array : 
 [[2 1 3]
 [5 4 6]
 [8 7 9]]


In [45]:
#7 Reversing the columns of a 2D array 
r=np.array([[1,2,3],[4,5,6],[7,8,9]])
r

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
flipped_arr = np.fliplr(r)
 
print('Array before changing column order:\n', r)
print('\nArray after changing column order:\n', flipped_arr)

Array before changing column order:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after changing column order:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [50]:
#7 or we can use this method too
# Get a reversed view of numpy array
reverse = np.flip(r[::-1])
reverse

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [55]:
np.flip(r[::1])

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [59]:
#8 Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10 
d = np.random.random((5,5))

print("Original Array:")
print(d) 


Original Array:
[[0.05567022 0.44443987 0.99497766 0.79770698 0.66451178]
 [0.43490211 0.18847526 0.74948139 0.22863097 0.24388836]
 [0.70799332 0.06163328 0.82924234 0.41249998 0.3511572 ]
 [0.41197145 0.76762925 0.57118479 0.17302669 0.06410567]
 [0.75993507 0.07766471 0.82396239 0.93920098 0.35315715]]


In [63]:
array = np.random.uniform(low=5,high=10,size=(5,3))
print(" Array filled with random values : \n", array);

 Array filled with random values : 
 [[7.83159323 9.35721045 6.51343979]
 [9.43567538 8.88976765 7.35668343]
 [9.89992084 5.16347133 9.78537647]
 [7.76880637 8.0700573  9.11958191]
 [7.53578256 9.24489557 7.83291049]]


In [65]:
#9 Create a 2d array with 1 on the border and 0 inside
x = np.ones((10,10))
print("Original x:")
print(x)
print(" border 1 and inside 0")
x[1:-1,1:-1] = 0
print(x)

Original x:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
 border 1
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [72]:
#Write script to produce the desired output. Use of fancy indexing is must.  
X = np.array([[ 9,   1,  12,  3], [ 14,  15,  6,  7], [ 18,  9,  10, 11]]) 
X

array([[ 9,  1, 12,  3],
       [14, 15,  6,  7],
       [18,  9, 10, 11]])

In [71]:
row=np.array([0,1,2])
col=np.array([2,0,3])
print("row:",row)
print("col:",col)
X[row,col]

row: [0 1 2]
col: [2 0 3]


array([12, 14, 11])