# fancy indexing

In [1]:
import numpy as np

In [2]:
rand=np.random.RandomState(42)
x=rand.randint(100,size=10)
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [3]:
[x[3],x[5],x[6]]

[71, 20, 82]

In [4]:
ind=[3,7,2]
x[ind]

array([71, 86, 14])

when using fancy indexing the shape of the result reflects the shape of the index arrays rather  than the shape of the array being indexed

In [6]:
ind=np.array([[3,7],[4,5]])
print(ind)
x[ind]

[[3 7]
 [4 5]]


array([[71, 86],
       [60, 20]])

fancy indexing also works in multiple dimensions.

In [12]:
p=np.arange(12).reshape((3,4))
p

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
row=np.array([0,1,2])
col=np.array([2,1,2])
print("row:",row)
print("col:",col)
p[row,col]

row: [0 1 2]
col: [2 1 2]


array([ 2,  5, 10])

combined indexing

In [16]:
p[2,[2,0,1]]

array([10,  8,  9])

In [29]:
mask=np.array([1,0,1,0],dtype=bool)
print(mask)
print("\n")
print("row:",row)
print("\n")
print(p)
print("\n")
print(row[:,np.newaxis])
print("\n")
p[row[:,np.newaxis],mask]

[ True False  True False]


row: [0 1 2]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[0]
 [1]
 [2]]




array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

modifying values with fancy indexing

In [26]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
i=np.array([2,1,8,4])
x[i]=99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


# structured data:Numpy's structured array

In [31]:
name=["alice","Bob","Catchyy","Doug"]
age=[25,45,32,24]
weight=[55.0,85.5,68.0,61.5]

In [32]:
x=np.zeros(4,dtype=int)
x

array([0, 0, 0, 0])

In [33]:
# Use a compound data type for structured arrays
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


Here 'U10' translates to "Unicode string of maximum length 10," 'i4' translates to "4-byte (i.e., 32 bit) integer," and 'f8' translates to "8-byte (i.e., 64 bit) float." We'll discuss other options for these type codes in the following section.

In [34]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('alice', 25, 55. ) ('Bob', 45, 85.5) ('Catchyy', 32, 68. )
 ('Doug', 24, 61.5)]


In [35]:
# Get all names
data['name']

array(['alice', 'Bob', 'Catchyy', 'Doug'], dtype='<U10')

In [36]:
# Get first row of data
data[0]

('alice', 25, 55.)

In [37]:
# Get the name from the last row
data[-1]['name']

'Doug'

In [39]:
### Get names where age is under 30
data[data['age'] < 30]['name']

array(['alice', 'Doug'], dtype='<U10')

In [49]:
###geṭ all the names 60<weight<90
data[(data['weight']>60) & (data['weight']<90)]['name']

array(['Bob', 'Catchyy', 'Doug'], dtype='<U10')

Creating Structured Arrays
Structured array data types can be specified in a number of ways. Earlier, we saw the dictionary method:

In [50]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [51]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [52]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [53]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])