In [2]:
import numpy as np

In [3]:
#integer array
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [6]:
data=[[1,4,2],[5,3,6]]
arr=np.array(data)
arr

array([[1, 4, 2],
       [5, 3, 6]])

In [9]:
arr.ndim

2

In [10]:
arr.shape

(2, 3)

In [11]:
arr.dtype

dtype('int32')

In [14]:
np.array([2.3,4.5,6.3],dtype = "float16")

array([2.3, 4.5, 6.3], dtype=float16)

In [15]:
np.zeros(10,dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [17]:
#create 
np.zeros(10,dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [18]:

np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
#create  a 3x5 floating point array filled with ones
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
#create array filled with a linear sequence
#starting with 0 , end with 20 and stepping by 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
#create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.full((2,3), fill_value=4)

array([[4, 4, 4],
       [4, 4, 4]])

In [5]:
np.random.seed(0) #seed for reprodicibility

x1=np.random.randint(10, size=6) #1 dim 
x2=np.random.randint(10, size=(3,4)) #2 dim
x3=np.random.randint(10, size=(3,4,5)) #3 dim

print("one dimensional array", x1)
print("two dimensional array", x2)
print("three dimensional array", x3)

one dimensional array [5 0 3 3 7 9]
two dimensional array [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
three dimensional array [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [6]:
print("dim x1=",x1.ndim)
print("dim x2",x2.ndim)
print("dim x3",x3.ndim)

print("shape x1",x1.shape)
print("shape x2",x2.shape)
print("shape x3",x3.shape)

print("size x1",x1.size)
print("size x2",x2.size)
print("size x3",x3.size)

print("dtype x3",x3.dtype)

dim x1= 1
dim x2 2
dim x3 3
shape x1 (6,)
shape x2 (3, 4)
shape x3 (3, 4, 5)
size x1 6
size x2 12
size x3 60
dtype x3 int32


In [13]:
print("itemsize:",x3.itemsize,"bytes")
print("nbytes:",x3.nbytes,"bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [ ]:
x1=np.random.randint(10, size=6) 
x2=np.random.randint(10, size=(3,4))
x3=np.random.randint(10, size=(3,4,5)) 

In [14]:
x1

array([5, 0, 3, 3, 7, 9])

In [15]:
x1[1]

0

#mat[row,col]
#mat[row][col]

In [10]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [7]:
x2[1,2]

8

In [18]:
x2[2,-1]

7

In [19]:
x2[2,0]

1

In [20]:
x2[2,3]

7

In [21]:
x2[2][3]

7

In [24]:
x2[0,0]=12   #values can be also  modified
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

reshaping of arrays

start=0, stop =siZe of dimension step step=1

#[: ,lower bound:upper bound: step]

In [27]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x[:5]

array([0, 1, 2, 3, 4])

In [29]:
x[4:7]

array([4, 5, 6])

In [31]:
swap=np.array([[1,2,3],[4,5,6],[7,8,9]])
swap

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
swap.ndim
swap[:,::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [52]:
swap[:2,::]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
print(swap[::-1])

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [43]:
swap[:,::-2]

array([[3, 1],
       [6, 4],
       [9, 7]])

In [60]:
swap[:2,-2::-1]

array([[2, 1],
       [5, 4]])

In [58]:
swap[:2,:2]

array([[1, 2],
       [4, 5]])

In [61]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [65]:
x2_sub=x2[:2,:2] #modify this subarray , original array is changed
print(x2_sub)

[[99  5]
 [ 7  6]]


In [66]:
x2_sub[0,0]=99
print(x2_sub)

[[99  5]
 [ 7  6]]


#creating copy expliecitely use copy() method
original x2 will not change using copy 


In [67]:
x2_sub_copy=x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [68]:
x2_sub_copy[0,0]=42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [69]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [76]:
# the size of the initial array must match the size of reshaped array
grid=np.arange(1, 11).reshape((2,5))
print(grid)


grid.reshape(5,2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [77]:
#concatention of arrays
x=np.array([1,2,3])
y=np.array([4,5,6])

np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [78]:
z=[99,98,97]
np.concatenate([x,y,z])

array([ 1,  2,  3,  4,  5,  6, 99, 98, 97])

In [84]:
grid=np.array([[1,2,3],[4,5,6]])
grid


array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [87]:
#concatenate along the second axis 
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [92]:
x=np.array([1,2,3])
grid=np.array([[4,5,6],[7,8,9]])

In [93]:
#vertically stack arrays
np.vstack([x,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
#horizontal stack arrays
y=np.array([[99],[99]])
np.hstack([y,grid])

array([[99,  4,  5,  6],
       [99,  7,  8,  9]])

In [101]:
a=np.arange(9)
print('first array:')
print(a)
print("\n")
print('split the array in 3 equal sized subarrays:')
b=np.split(a,3)
print(b)

first array:
[0 1 2 3 4 5 6 7 8]


split the array in 3 equal sized subarrays:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [103]:
print('split the array at positions indicated in 1-D array:')#i.e 4th place and at 7th place
c=np.split(a,[4,7])
print(c)

split the array at positions indicated in 1-D array:
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [110]:
grid=np.arange(16).reshape((4,4))
grid

#split vertically
upper, lower=np.vsplit(grid,[3])
print(upper)
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [111]:
#split horizontly
left,right=np.hsplit(grid,[3])
print(left)
print(right)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
[[ 3]
 [ 7]
 [11]
 [15]]
