# univeral function

In [2]:
import numpy as np

In [8]:
n=np.arange(9).reshape((3,3))
print(n)
2**n

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [ ]:
#unary function and binary function


In [9]:
np.add(n,2)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [10]:
np.floor_divide(n,2)

array([[0, 0, 1],
       [1, 2, 2],
       [3, 3, 4]], dtype=int32)

In [11]:
np.power(n,2)

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [12]:
np.mod(n,2)

array([[0, 1, 0],
       [1, 0, 1],
       [0, 1, 0]], dtype=int32)

In [13]:
x=np.array([-2,-1,0,1,2]) #absolute value 

abs(x)

array([2, 1, 0, 1, 2])

In [14]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [16]:
#np.linspace return evenly spaced numbers over a specified interval
theta=np.linspace(0,np.pi,3)
theta

array([0.        , 1.57079633, 3.14159265])

In [20]:
print("theta =",theta)
print("sin(theta) =",np.sin(theta))
print("cos(theta) =",np.cos(theta))
print("tan(theta) =",np.tan(theta))

theta = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [24]:
x=[-1,0,1]
print("x =",x)
print("arcsin(x)= ",np.arcsin(x))
print("arccos(x)= ",np.arccos(x))
print("arctan(x)= ",np.arctan(x))

x = [-1, 0, 1]
arcsin(x)=  [-1.57079633  0.          1.57079633]
arccos(x)=  [3.14159265 1.57079633 0.        ]
arctan(x)=  [-0.78539816  0.          0.78539816]


In [28]:
x=[1,2,3]
print("x =",x)
print("e^x =",np.exp(x))
print("2^x =",np.exp2(x))
print("3^x =",np.power(3,x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [29]:
x=[1,2,4,10]
print("x =",x)
print("ln(x) =",np.log(x))
print("log2(x) =",np.log2(x))
print("log10(x)=",np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x)= [0.         0.30103    0.60205999 1.        ]


In [34]:
x=[0,0.001,0.01,0.1]
print("exp(x)-1=",np.expm1(x))
print("log(1+x)=",np.log1p(x))


exp(x)-1= [0.         0.0010005  0.01005017 0.10517092]
log(1+x)= [0.         0.0009995  0.00995033 0.09531018]


In [36]:
x=np.arange(1,6)
print(x)
print(np.add.reduce(x))
print(np.multiply.reduce(x))

[1 2 3 4 5]
15
120


In [37]:
#to store allthe intermidiate results of the computation 
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

# aggregate function

In [53]:
l=np.random.random(100)
print(l)
sum(l)

[7.55247840e-01 7.96539634e-04 4.79520185e-01 9.22285627e-02
 7.08858290e-01 2.90426224e-01 3.52827962e-01 9.39593381e-02
 4.10355270e-01 5.91576431e-01 8.03935639e-01 7.95146085e-01
 6.38527835e-01 6.62179936e-01 2.01764666e-01 7.39639316e-02
 7.74520640e-01 5.16342158e-01 5.45971890e-01 6.09157377e-01
 8.10744135e-01 6.02435244e-02 3.57840112e-01 6.65603224e-01
 6.32361645e-02 1.68756507e-01 8.09142106e-01 7.12056512e-01
 5.49943734e-01 2.10562726e-01 7.55587142e-01 5.84914079e-01
 5.11456490e-01 9.12082317e-01 3.01342266e-01 4.52675849e-01
 1.12807983e-02 6.60402547e-01 5.84688013e-01 6.50670535e-01
 5.73628759e-01 4.41357964e-01 8.13700801e-01 4.43423958e-01
 8.84214398e-01 3.19438285e-01 5.69706422e-02 6.49310395e-01
 6.56739607e-01 8.60239597e-01 7.74166141e-01 7.23257673e-01
 3.97835630e-01 9.51828549e-01 4.11068285e-01 8.69322252e-01
 5.57788229e-01 8.95442799e-01 5.39751454e-01 8.48926974e-01
 3.43075950e-01 6.14601370e-01 3.65824141e-01 6.72617014e-01
 4.13434342e-01 7.709131

53.89090771263698

In [54]:
#numpy
big_array=np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

121 ms ± 17.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
672 µs ± 74.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [56]:
np.min(big_array)#np.max(big_array)

1.7880305438477961e-06

In [62]:
#multi dimensional aggregates
#axis=0 by column ,axis=1 means by row
m=np.random.random((3,4))
print(m)
print(m.min(axis=0))
print(m.max(axis=0))

[[0.58892228 0.03831411 0.01153434 0.74135754]
 [0.73253068 0.02243798 0.87050983 0.04337445]
 [0.59404039 0.04561541 0.33888847 0.91967234]]
[0.58892228 0.02243798 0.01153434 0.04337445]
[0.73253068 0.04561541 0.87050983 0.91967234]
